export * from "./RegistrationPage";
export * from "./AuthPage";
export * from "./HomePage";
export * from "./SearchPage";
export * from "./MoviePage";
export * from "./ProfilePage";
export * from "./SettingsPage";
export * from "./RecoveryPasswordPage";
export * from "./NotFoundPage";
